### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by xosemanolo** [amilajack/erb-video-example#3]
Video not playing

**Comment by leodesigndev** [comment]
same error

$yarn dev
// -> Error: Exited with code 2
    at ChildProcess.<anonymous> (C:\apps\erb-video-example\node_modules\cross-unzip\index.js:38:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[19296:0228/013449.656:ERROR:CONSOLE(2496)] "Uncaught SyntaxError: Unexpected token ...", source: chrome-extension://react-developer-tools/build/main.js (2496)


 
![erb_video](https://user-images.githubusercontent.com/56434221/155904802-55d5b5d0-03e7-400e-b6cd-f47246b8024d.PNG)
